"""profil enrichi + connexion google

Revision ID: 24e5db411f94
Revises:
Create Date: 2026-07-23 09:33:18.422312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '24e5db411f94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted pour SQLite ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('localisation', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(length=255), nullable=True))

    # SQLite ne supporte pas ALTER COLUMN directement — le mode "batch"
    # d'Alembic recrée la table en coulisses avec la nouvelle définition,
    # recopie toutes les lignes existantes, puis bascule. Aucune donnée
    # n'est perdue, c'est totalement transparent pour toi.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'hashed_password',
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
        )
        batch_op.create_index(
            batch_op.f('ix_users_google_id'), ['google_id'], unique=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted pour SQLite ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column(
            'hashed_password',
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
        )

    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'localisation')
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###